#!/bin/bash
USERNAME=$1
MDP=$2
admin=$4
server=$6
alias='www.'$server


#------------ INSTALLATION DE APACHE2 ------------#
apt-get install -qqy  apache2 apache2-doc apache2-utils
if [[ $? -eq 0 ]]
    then
        echo -e "\033[32mInstallation reussie du serveur apache2 et de apache2-doc\033[37m"
        #/etc/init.d/apache2 restart
        rootdirectory='\/srv\/www'

        mkdir /srv/pass
        htpasswd -cbs /srv/pass/phpmyadmin.passwd $USERNAME $MDP

        DIRECTORYEXECUTION=$( cd -P -- "$(dirname -- "$(command -v -- "$0")")" && pwd -P )
        mkdir /srv/www
        mkdir /var/www
        sudo adduser www-data
        sudo chown -Rf www-data:www-data /var/www
        sudo chown -Rf www-data:www-data /srv/www
        sudo find /var/www -type d -exec chmod 750 {} \;
        sudo find /var/www -type f -exec chmod 640 {} \;
        sudo find /srv/www -type d -exec chmod 750 {} \;
        sudo find /srv/www -type f -exec chmod 640 {} \;
        sudo chmod -R 644 /var/www
        sudo chmod -R 644 /srv/www
        sudo chmod a+X /var/www
        sudo chmod a+X /srv/www

        cp "$DIRECTORYEXECUTION"/apachefile/VHost /etc/apache2/sites-available/
        echo -e "\033[32mMise à jour du Virtual Host\033[37m"
        mv /etc/apache2/sites-available/default /etc/apache2/sites-available/default.orig
        cp "$DIRECTORYEXECUTION"/apachefile/default /etc/apache2/sites-available/

        sed -i 's/%admin%/'"$admin"'/' /etc/apache2/sites-available/VHost
        sed -i 's/%admin%/'"$admin"'/' /etc/apache2/sites-available/VHost
        sed -i 's/%admin%/'"$admin"'/' /etc/apache2/sites-available/VHost
        sed -i 's/%server%/'"$server"'/' /etc/apache2/sites-available/VHost
        sed -i 's/%alias%/'"$alias"'/' /etc/apache2/sites-available/VHost
        sed -i 's/%rootdirectory%/'"$rootdirectory"'/' /etc/apache2/sites-available/VHost

        a2ensite VHost

        if [[ $? -eq 0 ]]
            then
                echo " vhost had been successfully created"
        fi
        /etc/init.d/apache2 restart
        if [[ $? -eq 0 ]]
            then
                exit 0
        else
                echo -e "\033[31mEchec du redemarrage du serveur apache2\033[37m"
                exit 20
        fi
else
        echo -e "\033[31mEchec de l'installation apache2 et de apache2-doc\033[37m"
        exit 10
fi

