#!/bin/bash

DIRECTORYEXECUTION=$5
PROFTPD_MYSQL_PASS=$3
EMAIL=$4
#-----------Installation de ftp--------#
cat << PROFTPD_PRESEED | debconf-set-selections
proftpd-basic	shared/proftpd/inetd_or_standalone	select	standalone
PROFTPD_PRESEED

DEBIAN_FRONTEND='noninteractive' apt-get install -qqy proftpd proftpd-mod-mysql
if [ $? -eq 0 ]
then
	mkdir -p /srv/ssl/proftpd/certs
	mkdir -p /srv/ssl/proftpd/private
else
	echo -e "\033[31mEchec de l'installation de proftpd proftpd-mod-mysql\033[37m"
	exit 10
fi

echo "FR
FRANCE
PARIS
$SERVERNAME - FTP/SSL/TLS
$SERVERNAME - FTP/SSL/TLS
$SERVERNAME
$EMAIL
" | openssl req -x509 -nodes -days 3650 -newkey rsa:1024 -keyout /srv/ssl/proftpd/private/proftpd.key -out /srv/ssl/proftpd/certs/proftpd.crt

if [ $? -eq 0 ]
then
    mv /etc/proftpd/proftpd.conf /etc/proftpd/proftpd.conf.orig
else 
	echo -e "\033[31mEchec de l'obtention du certificat pour proftpd\033[37m"
	exit 20
fi

cp "$DIRECTORYEXECUTION"/file/ftpfile/*.conf /etc/proftpd/
if [ $? -eq 0 ]
then
	chmod 644 /etc/proftpd/*.conf
else
	echo -e "\033[31mEchec de la configuration de proftpd\033[37m"
	exit 10
fi

