#!/bin/bash

DIRECTORYEXECUTION=$5
PROFTPD_MYSQL_PASS=$3
USER=$1
MDP=$2
EMAIL=$4
#-----------Installation de ftp--------#
cat << PROFTPD_PRESEED | debconf-set-selections
proftpd-basic	shared/proftpd/inetd_or_standalone	select	standalone
PROFTPD_PRESEED

DEBIAN_FRONTEND='noninteractive' apt-get install -qqy proftpd proftpd-mod-mysql
if [ $? -eq 0 ]
then
	mkdir -p /srv/ssl/proftpd/certs
	mkdir -p /srv/ssl/proftpd/private
	groupadd ftpUser
	apt-get install -qqy whois
	MDPCRYPT=mkpasswd $MDP
	useradd --password $MDPCRYPT --groups ftpUser $USER
else
	echo -e "\033[31mEchec de l'installation de proftpd proftpd-mod-mysql\033[37m"
	exit 10
fi


cp "$DIRECTORYEXECUTION"/file/ftpfile/*.conf /etc/proftpd/
if [ $? -eq 0 ]
then
	chmod 644 /etc/proftpd/*.conf
else
	echo -e "\033[31mEchec de la configuration de proftpd\033[37m"
	exit 10
fi

